namespace BooksManager
{
    public enum EnumTagTask
    {
        EXPECTATION_TAG_START = 0,
        EXPECTATION_TAG_END = 1,
        EXPECTATION_TAG_NAME = 2,
        FORMING_TAG_NAME = 3,
        EXPECTATION_ATTRIBUT_NAME = 4,
        FORMING_ATTRIBUT_NAME = 5,
        EXPECTATION_ATTRIBUT_VALUE = 6,
        //FORMING_ATTRIBUT_VALUE = 7,
        EXPECTATION_TAG_VALUE = 8,
        FORMING_TAG_VALUE = 9,
        EXPECTATION_TAG_INCLUDE = 10,
        PASS_TAG_END = 11,
        DOCTYPE = 12,
        EXPECTATION_APOSTROPHE = 13, 
        EXPECTATION_QUOTATION_MARKS = 14
    }
}
